language: scala
scala:
  - 2.11.12
  - 2.12.11
  - 2.13.3
  - 3.0.0-M1
jdk:
  - openjdk8

install:
  - gem install sass
  - gem install jekyll -v 4.0.0

script:
  - sbt "++ ${TRAVIS_SCALA_VERSION}" test scalafmtSbtCheck scalafmtCheckAll
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.* ]]; then sbt "++ ${TRAVIS_SCALA_VERSION}" mimaReportBinaryIssues; fi
  - if [[ "$TRAVIS_SCALA_VERSION" == 2.12.* ]]; then sbt docs/makeMicrosite; fi
